---
title: "Variation Partitioning Bar Graph RMD"
author: "Thomas Van Zuiden"
date: "June 28, 2017"
output: html_document
---

## Using outputs from the Varition partitioning to create a good figure
#### These numbers are all from the results of the varpart analysis in the other RMD and html
```{r}
# morphology explains 0.04/0.386 =~10% of the 38% explained by the model.
# This will go in the first bar in the bar graph below
# the "0" is for the second bar of the bar graph
morph <- c(0.04076/0.38611,0) 
chem <- c(0.08042/0.38611,0)
clim <- c(0.01425/0.38611,0)
MEM <- c(0.12961/0.38611,0)
mo_ch <-c(0.07324/0.38611,0)
ch_cl <-c(0.02177/0.38611,0) 
ch_me <- c(0.02606/0.38611,0)
unexp <- c(0, 0.61389)
expl <- c(0, 0.38611)

(dor.var <- 0.04076+0.08042+0.01425+0.12961+0.07324+0.02177+0.02606)
(ela.var <- 0+0.09533+0.03944+0.0492+0+0.03603+0.00987+0.0360)

dat1 <- rbind(morph, chem, clim, MEM, mo_ch, ch_cl, ch_me,expl,unexp) ## combine data into matrix
```

### Creating the plot to show the variation explained of each fraction created above
```{r}
plot1 <- barplot(dat1, col= c(7,6,5,4,3,2,8,1,0), ylab="Variation explained", cex.lab = 1.2, cex.axis = 1.1) ##plot
legend(1.888,1, legend = c("chem + time","chem + clim","morph + chem","time period","climate","chemistry",
                           "morphology","explained","unexplained"),pch=22, pt.bg= c(8,2,3,4,5,6,7,1,0))
axis(1, plot1, c("Partioned Dorset Algal Variation", "Dorset Algae Variation Explained"), cex.axis=1.2)
box()
```